int _putchar(char c);
void _puts_recursion(char *t);
void _print_rev_recursion(char *t);
int _strlen_recursion(char *t);
int factorial(int r);
int _pow_recursion(int a, int b);
int square(int n, int val);
int _sqrt_recursion(int n);
int check_prime(int n, int resp);
int is_prime_number(int n);
int last_index(char *s);
int check(char *s, int start, int end, int pair);
int is_palindrome(char *s);
int checker(char *s1, char *s2, int a, int b, int wildUsed);
int wildcmp(char *s1, char *s2);
