int _putchar(char ch);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int ch);
int _isalpha(int ch);
int print_sign(int nu);
int _abs(int ch);
int print_last_digit(int nu);
void jack_bauer(void);
void times_table(void);
int add(int nu1, int nu2);
void print_to_98(int nu);
void print_to_98(int nu);
void print_times_table(int nu);
int main(void);
